name = input ("Enter your name")
print("This is your name")
name = input ("Enter your age")
print ("This is your age")
name = input ("Enter your roll no")
print ("This is your roll no")
name = input ("Enter your ph number")
print ("this is your phone number")
name = input ("Enter your nationality")
print ("This is your Nationality")